from pathlib import Path

from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent.parent

load_dotenv(BASE_DIR / ".env", override=True)

from core.config.paths_config import (
    ACCEL_PATH,
    ACCEL_SRC_PATH,
    RUNTIME_DIR,
    JOBS_DIR,
    UPLOADS_DIR,
    LOV_UPLOADS_DIR,
    PROFILE_MAP_UPLOADS_DIR,
)
from core.config.pipeline_config import (
    MAX_UPLOAD_SIZE_BYTES,
    UPLOAD_KINDS,
    UPLOAD_KIND_LABELS,
    UPLOAD_ALLOWED_EXTENSIONS,
    PROFILE_MAP_EXTENSIONS,
    LOV_FILE_EXTENSION,
    STAGING_FILE_EXTENSION,
    JOB_ARCHIVE_THRESHOLD,
    DEFAULT_PROJECT_NAME,
    DEFAULT_RUN_MODE,
    DEFAULT_CHUNK_SIZE,
    PROFILE_MAPPER_STEP,
    VALIDATOR_STEP,
    DEFAULT_DATABASE_CONNECT_TIMEOUT,
)
from core.config.server_config import (
    API_PREFIX,
    HOST,
    PORT,
    DEBUG,
    THREADED,
    ALLOWED_ORIGINS,
)
from core.config.auth_config import (
    DATABASE_URL,
    USERS_TABLE_SCHEMA,
    SESSION_COOKIE_NAME,
    SESSION_TTL_SECONDS,
    SESSION_COOKIE_SECURE,
    AUTH_ALLOW_LEGACY_PLAINTEXT,
)
from core.config.notifications_config import (
    NOTIFICATION_STREAM_POLL_SECONDS,
    NOTIFICATION_RETENTION_DAYS,
    RUN_NOTIFICATION_PURGE,
)
from core.config.connections_config import (
    CONNECTION_ENCRYPTION_KEY,
    RUN_CONNECTION_HEARTBEAT,
    CONNECTION_HEARTBEAT_INTERVAL_SECONDS,
    CONNECTION_ROTATION_REMINDER_DAYS,
)
from core.config.metadata_scan_config import (
    METADATA_SCAN_MAX_SCHEMAS,
    METADATA_SCAN_MAX_TABLES_PER_SCHEMA,
)
from core.config.data_quality_config import (
    DQ_DEFAULT_PARALLEL_TABLES,
    DQ_MAX_PARALLEL_TABLES,
    DQ_MAX_EXPRS_PER_PASS,
    DQ_RUN_WORKERS,
    DQ_DRY_RUN_MAX_TABLES,
    DQ_RESULTS_MAX_PAGE_SIZE,
)
from core.config.rule_catalog_config import VALID_RULE_IDS
from core.config.profile_map_config import (
    PROFILE_MAP_EDITABLE_FIELDS,
    PROFILE_MAP_TEXT_FIELD_MAX_LEN,
    PROFILE_MAP_NOTES_MAX_LEN,
)

__all__ = [
    "BASE_DIR",
    "ACCEL_PATH", "ACCEL_SRC_PATH", "RUNTIME_DIR",
    "JOBS_DIR", "UPLOADS_DIR", "LOV_UPLOADS_DIR",
    "PROFILE_MAP_UPLOADS_DIR",
    "MAX_UPLOAD_SIZE_BYTES", "UPLOAD_KINDS", "UPLOAD_KIND_LABELS",
    "UPLOAD_ALLOWED_EXTENSIONS", "PROFILE_MAP_EXTENSIONS", "LOV_FILE_EXTENSION",
    "STAGING_FILE_EXTENSION", "JOB_ARCHIVE_THRESHOLD", "DEFAULT_PROJECT_NAME",
    "DEFAULT_RUN_MODE", "DEFAULT_CHUNK_SIZE",
    "PROFILE_MAPPER_STEP", "VALIDATOR_STEP", "DEFAULT_DATABASE_CONNECT_TIMEOUT",
    "API_PREFIX", "HOST", "PORT", "DEBUG", "THREADED", "ALLOWED_ORIGINS",
    "DATABASE_URL", "USERS_TABLE_SCHEMA", "SESSION_COOKIE_NAME",
    "SESSION_TTL_SECONDS", "SESSION_COOKIE_SECURE", "AUTH_ALLOW_LEGACY_PLAINTEXT",
    "NOTIFICATION_STREAM_POLL_SECONDS", "NOTIFICATION_RETENTION_DAYS",
    "RUN_NOTIFICATION_PURGE",
    "CONNECTION_ENCRYPTION_KEY",
    "RUN_CONNECTION_HEARTBEAT", "CONNECTION_HEARTBEAT_INTERVAL_SECONDS",
    "CONNECTION_ROTATION_REMINDER_DAYS",
    "METADATA_SCAN_MAX_SCHEMAS", "METADATA_SCAN_MAX_TABLES_PER_SCHEMA",
    "DQ_DEFAULT_PARALLEL_TABLES", "DQ_MAX_PARALLEL_TABLES", "DQ_MAX_EXPRS_PER_PASS",
    "DQ_RUN_WORKERS", "DQ_DRY_RUN_MAX_TABLES", "DQ_RESULTS_MAX_PAGE_SIZE",
    "VALID_RULE_IDS",
    "PROFILE_MAP_EDITABLE_FIELDS", "PROFILE_MAP_TEXT_FIELD_MAX_LEN",
    "PROFILE_MAP_NOTES_MAX_LEN",
]
