import os


CONNECTION_ENCRYPTION_KEY = os.getenv("CONNECTION_ENCRYPTION_KEY", "")

RUN_CONNECTION_HEARTBEAT = (
    os.getenv("RUN_CONNECTION_HEARTBEAT", "true").strip().lower() == "true"
)

CONNECTION_HEARTBEAT_INTERVAL_SECONDS = int(
    os.getenv("CONNECTION_HEARTBEAT_INTERVAL_SECONDS", str(60 * 60))
)

CONNECTION_ROTATION_REMINDER_DAYS = int(
    os.getenv("CONNECTION_ROTATION_REMINDER_DAYS", "90")
)
