import os


NOTIFICATION_STREAM_POLL_SECONDS = float(os.getenv("NOTIFICATION_STREAM_POLL_SECONDS", "3"))

NOTIFICATION_RETENTION_DAYS = int(os.getenv("NOTIFICATION_RETENTION_DAYS", "7"))

RUN_NOTIFICATION_PURGE = os.getenv("RUN_NOTIFICATION_PURGE", "true").strip().lower() == "true"
